/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlfabetoRouteImport } from './routes/alfabeto'
import { Route as FrasesRouteImport } from './routes/frases'
import { Route as GramaticaRouteImport } from './routes/gramatica'
import { Route as LeituraRouteImport } from './routes/leitura'
import { Route as NumerosRouteImport } from './routes/numeros'
import { Route as PraktikaRouteImport } from './routes/praktika'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlfabetoRoute = AlfabetoRouteImport.update({
  id: '/alfabeto',
  path: '/alfabeto',
  getParentRoute: () => rootRouteImport,
} as any)
const FrasesRoute = FrasesRouteImport.update({
  id: '/frases',
  path: '/frases',
  getParentRoute: () => rootRouteImport,
} as any)
const GramaticaRoute = GramaticaRouteImport.update({
  id: '/gramatica',
  path: '/gramatica',
  getParentRoute: () => rootRouteImport,
} as any)
const LeituraRoute = LeituraRouteImport.update({
  id: '/leitura',
  path: '/leitura',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerosRoute = NumerosRouteImport.update({
  id: '/numeros',
  path: '/numeros',
  getParentRoute: () => rootRouteImport,
} as any)
const PraktikaRoute = PraktikaRouteImport.update({
  id: '/praktika',
  path: '/praktika',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alfabeto': typeof AlfabetoRoute
  '/frases': typeof FrasesRoute
  '/gramatica': typeof GramaticaRoute
  '/leitura': typeof LeituraRoute
  '/numeros': typeof NumerosRoute
  '/praktika': typeof PraktikaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alfabeto': typeof AlfabetoRoute
  '/frases': typeof FrasesRoute
  '/gramatica': typeof GramaticaRoute
  '/leitura': typeof LeituraRoute
  '/numeros': typeof NumerosRoute
  '/praktika': typeof PraktikaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alfabeto': typeof AlfabetoRoute
  '/frases': typeof FrasesRoute
  '/gramatica': typeof GramaticaRoute
  '/leitura': typeof LeituraRoute
  '/numeros': typeof NumerosRoute
  '/praktika': typeof PraktikaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alfabeto'
    | '/frases'
    | '/gramatica'
    | '/leitura'
    | '/numeros'
    | '/praktika'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alfabeto'
    | '/frases'
    | '/gramatica'
    | '/leitura'
    | '/numeros'
    | '/praktika'
  id:
    | '__root__'
    | '/'
    | '/alfabeto'
    | '/frases'
    | '/gramatica'
    | '/leitura'
    | '/numeros'
    | '/praktika'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlfabetoRoute: typeof AlfabetoRoute
  FrasesRoute: typeof FrasesRoute
  GramaticaRoute: typeof GramaticaRoute
  LeituraRoute: typeof LeituraRoute
  NumerosRoute: typeof NumerosRoute
  PraktikaRoute: typeof PraktikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alfabeto': {
      id: '/alfabeto'
      path: '/alfabeto'
      fullPath: '/alfabeto'
      preLoaderRoute: typeof AlfabetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frases': {
      id: '/frases'
      path: '/frases'
      fullPath: '/frases'
      preLoaderRoute: typeof FrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gramatica': {
      id: '/gramatica'
      path: '/gramatica'
      fullPath: '/gramatica'
      preLoaderRoute: typeof GramaticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitura': {
      id: '/leitura'
      path: '/leitura'
      fullPath: '/leitura'
      preLoaderRoute: typeof LeituraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeros': {
      id: '/numeros'
      path: '/numeros'
      fullPath: '/numeros'
      preLoaderRoute: typeof NumerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praktika': {
      id: '/praktika'
      path: '/praktika'
      fullPath: '/praktika'
      preLoaderRoute: typeof PraktikaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlfabetoRoute: AlfabetoRoute,
  FrasesRoute: FrasesRoute,
  GramaticaRoute: GramaticaRoute,
  LeituraRoute: LeituraRoute,
  NumerosRoute: NumerosRoute,
  PraktikaRoute: PraktikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
